print("srishti")
print('srishti')
print(""'srishti')
print('srishti'"")
print(""""srishti""")
print("srishti, kumari,""lohani, ")
print("srisht\noqwn\nshjansda")
print("srisht\toqwn\tshjansda")
print("srisht\roqwn\rshjansda")